services:
  db:
    image: postgres
    env_file:
      - backend/dotenv_files/.env
  web:
    build: ./backend
    command: /scripts/commands.sh
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/dotenv_files/.env
  test:
    build: ./backend
    command: python manage.py test
    volumes:
      - ./backend:/code
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    depends_on:
      - db
    env_file:
      - backend/dotenv_files/.env
