services:
  db:
    image: postgres
    env_file:
      - backend/dotenv_files/.env
  web:
    build: ./backend
    command: /scripts/commands.sh
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/dotenv_files/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules- frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - web

volumes:
  frontend_node_modules:
  # test:
  #   build: ./backend
  #   command: python manage.py test
  #   volumes:
  #     - ./backend:/code
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=project.settings
  #   depends_on:
  #     - db
  #   env_file:
  #     - backend/dotenv_files/.env
