services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=test-key
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - POSTGRES_ENGINE=django.db.backends.postgresql
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432