services:
  db:
    image: postgres
    env_file:
      - backend/dotenv_files/.env
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
      - media_data:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/dotenv_files/.env
    stop_grace_period: 1s

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # test:
  #   build: ./backend
  #   command: python manage.py test
  #   volumes:
  #     - ./backend:/code
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=project.settings
  #   depends_on:
  #     - db
  #   env_file:
  #     - backend/dotenv_files/.env

volumes:
  frontend_node_modules:
  media_data:
