# Generated by Django 5.1.7 on 2025-04-06 23:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (0-5 stars)')),
                ('message', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route Feedback',
                'verbose_name_plural': 'Route Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=200)),
                ('end_point', models.CharField(max_length=200)),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('feedbacks', models.ManyToManyField(blank=True, related_name='routes', to='core.feedbackroute')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pointofinterest')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_point_of_interest', to='core.route')),
            ],
            options={
                'ordering': ['distance'],
                'unique_together': {('route', 'point_of_interest')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='point_of_interest',
            field=models.ManyToManyField(related_name='routes', through='core.RoutePointOfInterest', to='core.pointofinterest'),
        ),
    ]
