# Generated by Django 5.2 on 2025-04-06 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoDeInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(help_text='Forma/função concreta do ponto (ex: restaurante, parque, etc)', max_length=100)),
                ('categoria', models.CharField(blank=True, help_text='Tema onde se encaixa (ex: lazer, cultura, etc)', max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('descricao', models.TextField(blank=True)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True)),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('ponto_de_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pontodeinteresse')),
            ],
        ),
    ]
