# Generated by Django 5.2 on 2025-04-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.AddField(
            model_name='route',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, related_name='routes', to='core.feedbackroute'),
        ),
    ]
