# Generated by Django 5.1.7 on 2025-04-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='RoutePointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pointofinterest')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
            options={
                'ordering': ['distance'],
                'unique_together': {('route', 'point_of_interest')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='point_of_interest',
            field=models.ManyToManyField(related_name='routes', through='core.RoutePointOfInterest', to='core.pointofinterest'),
        ),
    ]
