# Generated by Django 5.1.7 on 2025-04-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pointofinterest_remove_route_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routepointofinterest',
            options={'ordering': ['route']},
        ),
    ]
