# Generated by Django 5.1.7 on 2025-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_routepointofinterest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(help_text='Distance in kilometers'),
        ),
    ]
