# Generated by Django 5.2 on 2025-04-06 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_route_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routepointofinterest',
            options={'ordering': ['distance']},
        ),
        migrations.AlterField(
            model_name='routepointofinterest',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_point_of_interest', to='core.route'),
        ),
    ]
