# Generated by Django 5.0.6 on 2025-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starting_location', models.CharField(blank=True, max_length=255, null=True)),
                ('ending_location', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinates', models.JSONField(default=list, help_text='Array of geographic coordinates defining the route path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
