# Generated by Django 5.0.6 on 2025-05-26 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starting_location', models.CharField(blank=True, max_length=255)),
                ('ending_location', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.JSONField(default=list, help_text='Array of geographic coordinates defining the route path')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tags associated with the route')),
                ('image', models.ImageField(blank=True, help_text='An image representing this route', null=True, upload_to='route_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
