# Generated by Django 5.2 on 2025-05-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Array of tags associated with the route'),
        ),
    ]
