# Generated by Django 5.0.6 on 2025-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, help_text='An image representing this route', null=True, upload_to='route_images/'),
        ),
    ]
