# Generated by Django 5.2.2 on 2025-06-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='ending_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='starting_location',
            field=models.CharField(max_length=255),
        ),
    ]
