# Generated by Django 5.2.1 on 2025-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_route_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, help_text='An image representing this route', null=True, upload_to='route_images/'),
        ),
    ]
