# Generated by Django 5.2.1 on 2025-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_route_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='ending_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='starting_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
